/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Categoria;
import Model.Produto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class FrmCadastroProduto extends javax.swing.JDialog {
    boolean adicionarRegistroHabilitado = false;
    boolean alteraRegistroHabilitado = false;
    
    /**
     * Creates new form FrmCadastroProduto
     */
    public FrmCadastroProduto() {
        initComponents();
        this.setModal(true);
        this.setResizable(false);
        limpaCampos();
        preencheComboBox(0);
        jBCancelar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNomeProduto = new javax.swing.JTextField();
        jCBCategoria = new javax.swing.JComboBox();
        jLCodigoProduto = new javax.swing.JLabel();
        jFTFPreco = new javax.swing.JFormattedTextField();
        jBPesquisar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Produto"));

        jLabel1.setText("Código");

        jLabel3.setText("Nome:");

        jLabel4.setText("Preço:");

        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categoria" }));

        jLCodigoProduto.setText("1");

        jFTFPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Pesquisar.png"))); // NOI18N
        jBPesquisar.setToolTipText("Pesquisar Registro");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Remove.png"))); // NOI18N
        jBExcluir.setToolTipText("Apagar registro");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Editar.png"))); // NOI18N
        jBAlterar.setToolTipText("Alterar registro");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Add.png"))); // NOI18N
        jBAdd.setToolTipText("Adicionar Registro");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jLabel2.setText("R$");

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFNomeProduto)
                                .addComponent(jCBCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel2)
                                    .addGap(1, 1, 1)
                                    .addComponent(jFTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jBCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLCodigoProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jBCancelar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        try {
            DAL.DAO<Produto> novoRegistroProd = new DAL.DAO();
            
            if(adicionarRegistroHabilitado == true){
                if(!jTFNomeProduto.getText().equals("")){
                    if(jCBCategoria.getSelectedIndex() != 0){
                        if(!jFTFPreco.getText().equals("")){
                            
                            Produto newProduto = new Produto();
                            
                            newProduto.setDescricao(jTFNomeProduto.getText());
                            String selecionado = String.valueOf(jCBCategoria.getSelectedItem());
                            String[] codigoDaCategoria = selecionado.split("-");
                            newProduto.setCategoria_idCategoria(Integer.parseInt(codigoDaCategoria[0]));
                            newProduto.setPreco(Double.parseDouble(jFTFPreco.getText().replaceAll(",", ".")));
                            
                            novoRegistroProd.insertRegistro(newProduto);
                            
                           limpaCampos();
                        }else{
                            JOptionPane.showMessageDialog(null, "Informe um preço para o produto!");
                            jFTFPreco.requestFocus();
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Informe uma categoria!");
                        jCBCategoria.requestFocus();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Informe um nome para o produto!");
                    jTFNomeProduto.requestFocus();
                }
            }else{
                limpaCampos();
                
                String ultimoReg = novoRegistroProd.ultimoRegistro(Produto.class);
                
                jLCodigoProduto.setText(ultimoReg);
                jTFNomeProduto.setEditable(true);
                jCBCategoria.setEnabled(true);
                jFTFPreco.setEditable(true);
                
                jBCancelar.setVisible(true);
                
                adicionarRegistroHabilitado = true;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBAddActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        if(alteraRegistroHabilitado == true){
            try {
                
                DAL.DAO<Produto> dao = new DAL.DAO();
                Produto alterarProd = new Produto();
                alterarProd.setIdProduto(Integer.parseInt(jLCodigoProduto.getText()));
                alterarProd.setDescricao(jTFNomeProduto.getText());
                String selecionado = String.valueOf(jCBCategoria.getSelectedItem());
                String[] codigoDaCategoria = selecionado.split("-");
                alterarProd.setCategoria_idCategoria(Integer.parseInt(codigoDaCategoria[0]));
                alterarProd.setPreco(Double.parseDouble(jFTFPreco.getText().replaceAll(",", ".")));
                JOptionPane.showMessageDialog(null, "PReco: "+alterarProd.getPreco());
                dao.alterarRegistro(alterarProd);
                 
                limpaCampos();
                
                alteraRegistroHabilitado = false;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(!jTFNomeProduto.getText().equals("")){
                jTFNomeProduto.setEditable(true);
                jCBCategoria.setEnabled(true);
                jFTFPreco.setEditable(true);
                alteraRegistroHabilitado = true;
            }else{
                JOptionPane.showMessageDialog(null, "Escolha um produto para alterar!");
            }
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        try {
            FrmPesquisa frm = new FrmPesquisa(2);
            frm.setVisible(true);
            
            DAL.DAO<Produto> dao = new DAL.DAO();
            Produto prod = dao.consultaProduto(frm.getIdProduto());
            
            if(prod != null){
                jLCodigoProduto.setText(String.valueOf(prod.getIdProduto()));
                jTFNomeProduto.setText(prod.getDescricao());
                preencheComboBox(prod.getCategoria_idCategoria());
                jFTFPreco.setText(String.valueOf(prod.getPreco()));
                jBCancelar.setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        if(!jTFNomeProduto.getText().equals("")){
            try {
                
                DAL.DAO<Produto> dao = new DAL.DAO();
                dao.excluirRegistro(2, jLCodigoProduto.getText());
                
                limpaCampos();
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Escolha um registro para exlcusão!");
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        limpaCampos();
        jBCancelar.setVisible(false);
        adicionarRegistroHabilitado = false;
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JComboBox jCBCategoria;
    private javax.swing.JFormattedTextField jFTFPreco;
    private javax.swing.JLabel jLCodigoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFNomeProduto;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos(){
        jLCodigoProduto.setText("");
        jTFNomeProduto.setEditable(false);
        jTFNomeProduto.setText("");
        jCBCategoria.setSelectedIndex(0);
        jCBCategoria.setEnabled(false);
        jFTFPreco.setEditable(false);
        jFTFPreco.setText("");
    }
    
    /**
     * Serve para preencher o Combo Box com base em um ArrayList, porém se passar
     * um um valor para o selecionar irá deixar uma opção pré-selecionada
     * 0 - Não selecionar
     * <> 0  - Selecionar(Passar o codigo da Categoria)
     * @param selecionar 
     */
    public void preencheComboBox(int selecionar){
        jCBCategoria.removeAllItems();
        
        int indexParaSelecionar = 0;
        try {
            
            DAL.DAO<Produto> novoRegistroProd = new DAL.DAO();
            
            ArrayList<Categoria> lstCategoria = novoRegistroProd.todosRegistros(Categoria.class, 0);
            
            for (int i = 0; i < lstCategoria.size(); i++) {
                if(i == 0){
                    jCBCategoria.addItem("Categoria");
                }
                Categoria ob = lstCategoria.get(i);
                jCBCategoria.addItem(ob.getIdCategoria()+"-"+ob.getDescricao());
                indexParaSelecionar = i;
            }
            
            if(selecionar != 0){
                jCBCategoria.setSelectedIndex(indexParaSelecionar);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
