/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAL.DAO;
import Model.Categoria;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class FrmCadastroCategoria extends javax.swing.JDialog {
    /*Modo habilitado é quando apertar novamente irá fazer a edição*/
    boolean novoRegistroHabilitado = false;
    boolean alterandoRegistrosHabilitado = false;
    
    /**
     * Creates new form FrmManutencaoCategoria
     */
    public FrmCadastroCategoria() {
        initComponents();
        this.setModal(true);
        this.setResizable(false);
        jTFNomeCategoria.setEditable(false);
        jBCancelar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLCodigoCategoria = new javax.swing.JLabel();
        jTFNomeCategoria = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBAdd = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Categoria");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Categoria"));

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Pesquisar.png"))); // NOI18N
        jBPesquisar.setToolTipText("Pesquisar Registro");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Remove.png"))); // NOI18N
        jBExcluir.setToolTipText("Apagar registro");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Editar.png"))); // NOI18N
        jBAlterar.setToolTipText("Alterar registro");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Add.png"))); // NOI18N
        jBAdd.setToolTipText("Adicionar Registro");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNomeCategoria)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLCodigoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jBCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLCodigoCategoria))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jBCancelar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botão Adcionar: Se variavel novoRegistroHabilitado == true irá habilitar 
     * o jTFNomeCategoria para cadastrar a categoria e irá pegar o novo codigo 
     * para o novo cadastro com base no ultimo registro add mais um.
     * @param evt 
     */
    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        if(novoRegistroHabilitado == true){
            if(!jTFNomeCategoria.getText().equals("")){
                try {
                    Categoria novaCat = new Categoria();
                    novaCat.setDescricao(jTFNomeCategoria.getText());

                    DAO<Categoria> cat = new DAO<Categoria>();
                    cat.insertRegistro(novaCat);
                    
                    jLCodigoCategoria.setText("");
                    jTFNomeCategoria.setText("");
                    jTFNomeCategoria.setEditable(false);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrmCadastroCategoria.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmCadastroCategoria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Informe um nome para categoria!");
                jTFNomeCategoria.requestFocus();
            }
        }else{
            try {
                jBCancelar.setVisible(true);
                DAO<Categoria> cat = new DAO<Categoria>();
                String ultimoRegistro = cat.ultimoRegistro(Categoria.class);
                jLCodigoCategoria.setText(ultimoRegistro);
                jTFNomeCategoria.setEditable(true);
                jTFNomeCategoria.requestFocus();
                
                novoRegistroHabilitado = true;
                
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Problema com comando FrmCadastroCategoria:\n"+ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Problema com comando FrmCadastroCategoria:\n"+ex);
            }
        }
    }//GEN-LAST:event_jBAddActionPerformed

    /**
     * Botão Pesquisar: Irá abrir o FrmPesquisa com a listagem das categorias
     * e após selecionar irá retornar um frm.getIdRegistro() e frm.getNomeRegistro()
     * com o id e o nome da categoria selecionada.
     * @param evt 
     */
    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        FrmPesquisa frm = new FrmPesquisa(1);
        frm.setVisible(true);
        if(frm.getIdRegistro() > 0){
            jLCodigoCategoria.setText(String.valueOf(frm.getIdRegistro()));
            jTFNomeCategoria.setText(frm.getNomeRegistro());
            jBCancelar.setVisible(true);
        }        
    }//GEN-LAST:event_jBPesquisarActionPerformed

    /**
     * Botão Alterar: Se habilitado irá alterar o registro no banco de dados com 
     * base no que foi escrito no jTFNomeCategoria
     * @param evt 
     */
    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        if(alterandoRegistrosHabilitado == true){
            try {
                DAL.DAO<Categoria> alterandoRegistro = new DAL.DAO();
                Categoria alterCat = new Categoria();
                
                alterCat.setIdCategoria(Integer.parseInt(jLCodigoCategoria.getText()));
                alterCat.setDescricao(jTFNomeCategoria.getText());
                
                alterandoRegistro.alterarRegistro(alterCat);
                
                jLCodigoCategoria.setText("");
                jTFNomeCategoria.setText("");
                jTFNomeCategoria.setEditable(false);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadastroCategoria.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadastroCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(!jTFNomeCategoria.getText().isEmpty()){
                jTFNomeCategoria.setEditable(true);
                alterandoRegistrosHabilitado = true;
            }else{
                JOptionPane.showMessageDialog(null, "Necessário escolher um registro para alterar");
            }
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    /**
     * Irá excluir o registro com base no jTFNomeCategoria e jLCodigoCategoria 
     * @param evt 
     */
    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        if(!jTFNomeCategoria.getText().isEmpty()){
            try {
                DAL.DAO<Categoria> excluirCat = new DAL.DAO();
                
                Categoria catExcluir = new Categoria();
                catExcluir.setIdCategoria(Integer.parseInt(jLCodigoCategoria.getText()));
                catExcluir.setDescricao(jTFNomeCategoria.getText());
                
                excluirCat.excluirRegistro(1, catExcluir);
                
                jLCodigoCategoria.setText("");
                jTFNomeCategoria.setText("");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadastroCategoria.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadastroCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Escolha um registro para a exclusão!");
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        jLCodigoCategoria.setText("");
        jTFNomeCategoria.setText("");
        jBCancelar.setVisible(false);
        alterandoRegistrosHabilitado = false;
        novoRegistroHabilitado = false;
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLCodigoCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFNomeCategoria;
    // End of variables declaration//GEN-END:variables
}
