/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.BotThread;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLImagemFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMStatusConexao = new javax.swing.JMenu();
        jMCadastro = new javax.swing.JMenu();
        jMICadastroProduto = new javax.swing.JMenuItem();
        jMICadastroCategoria = new javax.swing.JMenuItem();
        jMISair = new javax.swing.JMenuItem();
        jMManutencao = new javax.swing.JMenu();
        jMIManutencaoPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lancheria Pé de Fava");

        jLImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/ImagemPrincipalComLogo.png"))); // NOI18N

        jMStatusConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Desconectado.png"))); // NOI18N
        jMenuBar1.add(jMStatusConexao);

        jMCadastro.setText("Cadastro");

        jMICadastroProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMICadastroProduto.setText("Cadastro de Produto");
        jMICadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroProdutoActionPerformed(evt);
            }
        });
        jMCadastro.add(jMICadastroProduto);

        jMICadastroCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMICadastroCategoria.setText("Cadastro de Categoria");
        jMICadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroCategoriaActionPerformed(evt);
            }
        });
        jMCadastro.add(jMICadastroCategoria);

        jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMCadastro.add(jMISair);

        jMenuBar1.add(jMCadastro);

        jMManutencao.setText("Manutenção");

        jMIManutencaoPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMIManutencaoPedido.setText("Manutenção Pedidos");
        jMIManutencaoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManutencaoPedidoActionPerformed(evt);
            }
        });
        jMManutencao.add(jMIManutencaoPedido);

        jMenuBar1.add(jMManutencao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLImagemFundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLImagemFundo)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMICadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroCategoriaActionPerformed
        FrmCadastroCategoria frm = new FrmCadastroCategoria();
        frm.setVisible(true);
    }//GEN-LAST:event_jMICadastroCategoriaActionPerformed

    private void jMICadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroProdutoActionPerformed
        FrmCadastroProduto frm = new FrmCadastroProduto();
        frm.setVisible(true);
    }//GEN-LAST:event_jMICadastroProdutoActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        dispose();
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMIManutencaoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManutencaoPedidoActionPerformed
        FrmConsultaPedido frm = new FrmConsultaPedido();
        frm.setVisible(true);
    }//GEN-LAST:event_jMIManutencaoPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
        
        try {
            DAL.Conexao conec = new DAL.Conexao();
            if(conec.testaConexao() == true){
                ImageIcon img = new ImageIcon("build\\classes\\View\\imagens\\Conectado.png");
                jMStatusConexao.setToolTipText("Conectado!");                
                jMStatusConexao.setIcon(img);
                Thread th = new BotThread();
                th.start();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Problema na conexão no banco de dados");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema na conexão no banco de dados");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLImagemFundo;
    private javax.swing.JMenu jMCadastro;
    private javax.swing.JMenuItem jMICadastroCategoria;
    private javax.swing.JMenuItem jMICadastroProduto;
    private javax.swing.JMenuItem jMIManutencaoPedido;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenu jMManutencao;
    private static javax.swing.JMenu jMStatusConexao;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}