/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Categoria;
import Model.Produto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author William
 */
public class FrmPesquisa extends javax.swing.JDialog {
    int tela = 0;
    
    /*Classe da categoria*/
    private int idRegistro;
    private String nomeRegistro;
    
    /*Classe do produto*/
    private int idProduto;
    private String descricao;
    private double preco;
    
    
    /**
     * Tela recebe a origem da mesma e com isso realiza um select no banco com 
     * todos os dados do produtos ou das categorias.
     * tela = 1 - Cadastro de categoria
     * tela = 2 - Cadastro de produto
     * @param tela
     */
    public FrmPesquisa(int tela) {
        this.setResizable(false);
        this.tela = tela;
        try {
            initComponents();
            this.setModal(true);
            DefaultListModel dlm = new DefaultListModel();
            
            DAL.DAO dao = new DAL.DAO<Categoria>();
            
            if(tela == 1){
                ArrayList<Categoria> lstCategorias = dao.todosRegistros(Categoria.class, 0, 0);
                jList.setToolTipText("Lista de Categorias");
                if(!lstCategorias.isEmpty()){
                    for (int i = 0; i < lstCategorias.size(); i++) {
                        dlm.add(i, lstCategorias.get(i).getIdCategoria()+"-"+lstCategorias.get(i).getDescricao());
                    }
                }
            }else if(tela == 2){
                ArrayList<Produto> lstProduto = dao.todosRegistros(Produto.class, 0, 0);
                jList.setToolTipText("Lista de Produtos");
                if(!lstProduto.isEmpty()){
                    for (int j = 0; j < lstProduto.size(); j++) {
                        dlm.add(j, lstProduto.get(j).getIdProduto()+"-"+lstProduto.get(j).getDescricao());
                    }
                }
            }
            jList.setModel(dlm);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmPesquisa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPesquisa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jBOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Pesquisa");

        jList.setToolTipText("");
        jScrollPane1.setViewportView(jList);

        jBOk.setText("Ok");
        jBOk.setToolTipText("Selecionar registro");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBOk)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Tratamento do clique do botão "Ok" que ira pegar e fazer um split 
     * do id e nome do produto/categorai, com base no valor do int TELA
     * @param evt 
     */
    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        DefaultListModel dlm = new DefaultListModel();
        dlm.addElement(jList.getSelectedValue());
        String selecionado = String.valueOf(dlm);
        selecionado = selecionado.substring(1, (selecionado.length()-1));
       
        if(!selecionado.equals("null")){
            if(tela == 1){
                    String[] vet = selecionado.split("-");
                    idRegistro = Integer.parseInt(vet[0]);
                    nomeRegistro = vet[1];
            }else{
                String[] vet = selecionado.split("-");
                idProduto = Integer.parseInt(vet[0]);
            }    
        }
        dispose();
    }//GEN-LAST:event_jBOkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOk;
    private javax.swing.JList jList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public int getIdRegistro() {
        return idRegistro;
    }

    public String getNomeRegistro() {
        return nomeRegistro;
    }

    public int getIdProduto() {
        return idProduto;
    }

    public String getDescricao() {
        return descricao;
    }

    public double getPreco() {
        return preco;
    }
}
